version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8180:8180"
    environment:
      - LEONLIB_DB_PATH=/var/lib/appdata/leonlib.db
      - LEONLIB_CAPTCHA_SITE_KEY=${LEONLIB_CAPTCHA_SITE_KEY}
      - LEONLIB_CAPTCHA_SECRET_KEY=${LEONLIB_CAPTCHA_SECRET_KEY}
      - LEONLIB_GOOGLE_OAUTH_CLIENT_ID=${LEONLIB_GOOGLE_OAUTH_CLIENT_ID}
      - LEONLIB_GOOGLE_OAUTH_CLIENT_SECRET=${LEONLIB_GOOGLE_OAUTH_CLIENT_SECRET}
      - LEONLIB_GOOGLE_OATH_CALLBACK=${LEONLIB_GOOGLE_OATH_CALLBACK}
      - DB_MODE=${DB_MODE}
      - PORT=8180
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - SESSION_SECRET=${SESSION_SECRET}
      - LEONLIB_MAINAPP_USER=${LEONLIB_MAINAPP_USER}

volumes:
  database-data:
