version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    container_name: app
    ports:
      - "8180:8180"
    environment:
      - LEONLIB_DB_PATH=/var/lib/appdata/leonlib.db
      - LEONLIB_CAPTCHA_SITE_KEY=${LEONLIB_CAPTCHA_SITE_KEY}
      - LEONLIB_CAPTCHA_SECRET_KEY=${LEONLIB_CAPTCHA_SECRET_KEY}
      - LEONLIB_GOOGLE_OAUTH_CLIENT_ID=${LEONLIB_GOOGLE_OAUTH_CLIENT_ID}
      - LEONLIB_GOOGLE_OAUTH_CLIENT_SECRET=${LEONLIB_GOOGLE_OAUTH_CLIENT_SECRET}
      - LEONLIB_GOOGLE_OATH_CALLBACK=${LEONLIB_GOOGLE_OATH_CALLBACK}
      - DB_MODE=${DB_MODE}
      - RUN_MODE=${RUN_MODE}
      - PORT=8180
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - SESSION_SECRET=${SESSION_SECRET}
      - LEONLIB_MAINAPP_USER=${LEONLIB_MAINAPP_USER}
      - USE_ANALYTICS=${USE_ANALYTICS}

  matomo:
    image: matomo:latest
    container_name: matomo
    ports:
      - "80:80"
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_NAME=matomo_db
      - MATOMO_DATABASE_USER=matomo_user
      - MATOMO_DATABASE_PASSWORD=matomo_password
    volumes:
      - matomo_data:/var/www/html
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_DATABASE=matomo_db
      - MYSQL_USER=matomo_user
      - MYSQL_PASSWORD=matomo_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  database-data:
  matomo_data:
  db_data:
